server:
    port: 9090

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/${MYSQL_ENV_MYSQL_DATABASE}
    username: ${MYSQL_ENV_MYSQL_USER}
    password: ${MYSQL_ENV_MYSQL_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    root: INFO
  file: /tmp/log/springTest.log