mysql_data:
  container_name: mysql_data
  image: tianon/true
  volumes:
    - /var/lib/mysql
    - /var/lib/mysql-files

embedded-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=s3cr3t
    - MYSQL_DATABASE=SPRING_TEST
    - MYSQL_USER=test
    - MYSQL_PASSWORD=pass
  volumes_from:
    - mysql_data
  ports:
    - 3307:3306

spring-boot-jpa-docker-webapp:
  image: tatane/docker-test
  links:
    - embedded-mysql:mysql
  ports:
    - 9091:9090